real_estate_openimmo.source.*:
  type: config_entity
  label: 'OpenImmo Source config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    feed_type:
      type: string
      label: 'Source type'
    feed_config:
      type: real_estate_openimmo.feed.[%parent.feed_type]
    queries:
      type: sequence
      sequence:
        type: mapping
        mapping:
          id:
            type: string
          label:
            type: label
            label: 'Label'
          uuid:
            type: string
          weight:
            type: integer
            label: 'Weight'
          key_field:
            type: string
            label: 'Key Field'
          entity:
            type: string
            label: 'Entity'
          select:
            type: text
            label: 'Select'

real_estate_openimmo.feed.*:
  type: mapping
  label: 'OpenImmo Source'

real_estate_openimmo.feed.file:
  type: mapping
  label: 'File'
  mapping:
    file_path:
      type: string
      label: 'File path'

real_estate_openimmo.feed.ftp:
  type: mapping
  label: 'FTP'
  mapping:
    username:
      type: string
      label: 'User name'
    password:
      type: string
      label: 'Password'
    hostname:
      type: string
      label: 'Hostname'
    port:
      type: string
      label: 'Port'
    server_path:
      type: string
      label: 'Server Path'
