real_estate_rets.real_estate_rets_connection.*:
  type: config_entity
  label: 'RETS Connection config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    login_url:
      type: string
      label: 'Login URL'
    username:
      type: string
      label: 'User Name'
    password:
      type: string
      label: 'Password'
    rets_version:
      type: string
      label: 'Rets Version'
    user_agent:
      type: string
      label: 'User Agent'
    user_agent_password:
      type: string
      label: 'User Agent Password'
    http_authentication:
      type: string
      label: 'HTTP Authentication'
    use_post_method:
      type: string
      label: 'Use POST Method'
    disable_follow_location:
      type: string
      label: 'Disable Follow Location'
    queries:
      type: sequence
      sequence:
        type: mapping
        mapping:
          id:
            type: string
          label:
            type: label
            label: 'Label'
          uuid:
            type: string
          weight:
            type: integer
            label: 'Weight'
          resource:
            type: string
            label: 'Resource'
          class:
            type: string
            label: 'Class'
          query:
            type: string
            label: 'Query'
          dmql:
            type: text
            label: 'DMQL'
          format:
            type: string
            label: 'Format'
          limit:
            type: string
            label: 'Limit'
          standardnames:
            type: string
            label: 'Standard Names'
          key_field:
            type: string
            label: 'Key Field'
          entity:
            type: string
            label: 'Entity'
          select:
            type: text
            label: 'Select'
