real_estate_agency.real_estate_agency_type.*:
  type: config_entity
  label: 'Agency type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
